### ISSUE TITLE
data load issue

### ISSUE THREAD

**Issue by akashkumar398** [WorldofDataScience/machine_flow#5]
if i load a bigger file (for e:g: adult data-sets  having 48842 instances) then list_data function doesn't work as page become unresponsive because of data size.
how to handle this issue?

**Comment by sean-mcclure** [comment]
The application currently only reads data directly. You can dig into the node code to change the data piece to handle streaming. 

I’ll likely be coming out with an fully updated application soon, which will be able to handle streaming data.

**Comment by akashkumar398** [comment]
fixed this issue
